name: wishly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  intl: ^0.20.1
  workmanager: ^0.5.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  timezone: ^0.9.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
